[Task-803]-Change the description field as rich text editor in Kanban Board with collapse
ravenanhq/admina pull request #108
Opened 2024-07-17 10:12 UTC by rajiravenantech

Change the description field as rich text editor in Kanban Board with collapse

2024-07-18 07:19 UTC, shanmugapriyaravenantech requested changes
In files upload only image files can be uploaded. Need to upload other format files too

2024-07-31 09:35 UTC, karthicravenantech commented on src/app/components/AdvancedKanbanBoard/EditTask.tsx
> +                        dangerouslySetInnerHTML={{
Need to remove the dangerouslySetInnerHTML

2024-07-31 09:55 UTC, karthicravenantech commented
In comment text editior need to upload other format files like csv,pdf and txt, but its working only images

2024-07-31 10:45 UTC, karthicravenantech requested changes
Need to remove the dangerouslySetInnerHTML

2024-08-02 06:12 UTC, merged