[Task-23]-Implement import/export feature
ravenanhq/admina pull request #32
Opened 2024-01-20 09:57 UTC by rajiravenantech

Implement import/export feature

2024-01-20 10:48 UTC, shanmugapriyaravenantech requested changes
During import the data must be added to the json file and table must be loaded with the data from that json file

2024-01-22 06:10 UTC, rajiravenantech commented
> During import the data must be added to the json file and table must be loaded with the data from that json file

Display newly imported data and default JSON data.

2024-01-22 09:27 UTC, shanmugapriyaravenantech approved these changes

2024-01-23 07:09 UTC, esakkirajaravenantech approved these changes

2024-01-23 07:09 UTC, merged