[Task-26]-Implement table CRUD components and pages
ravenanhq/admina pull request #45
Opened 2024-02-12 10:28 UTC by rajiravenantech

Implement table CRUD components and pages

2024-02-14 12:56 UTC, esakkirajaravenantech commented on src/app/components/Crud/List.tsx
> +Link;
Remove this

2024-02-14 12:58 UTC, esakkirajaravenantech requested changes
Remove mentioned text

2024-02-15 04:41 UTC, rajiravenantech commented on src/app/components/Crud/List.tsx
> +Link;
Removed unwanted text.

2024-02-15 04:43 UTC, esakkirajaravenantech approved these changes

2024-02-15 04:43 UTC, merged