[Task-49]-Change the menu and button elements
ravenanhq/admina pull request #61
Opened 2024-03-21 09:46 UTC by rajiravenantech

Change the menu and button elements

2024-03-27 09:27 UTC, esakkirajaravenantech requested changes

2024-03-27 09:27 UTC, esakkirajaravenantech commented on src/app/components/Sidebar/Sidebar.tsx
> +  const [menuOpen, setMenuOpen] = React.useState(true);
Remove usused states.

2024-03-27 09:27 UTC, esakkirajaravenantech commented on src/app/components/Sidebar/Sidebar.tsx
>    const handleEcommerceClick = () => {
Remove console.log

2024-03-27 09:27 UTC, esakkirajaravenantech commented on src/app/components/Sidebar/Sidebar.tsx
>                  Admina
Add some modification to the name like increase font size, change colour and font family.

2024-03-27 09:27 UTC, esakkirajaravenantech commented on src/app/globals.css
> +  color: #fff;
Change active menu background color

2024-03-28 05:54 UTC, rajiravenantech commented on src/app/components/Sidebar/Sidebar.tsx
> +  const [menuOpen, setMenuOpen] = React.useState(true);
Removed unused state.

2024-03-28 05:54 UTC, rajiravenantech commented on src/app/components/Sidebar/Sidebar.tsx
>    const handleEcommerceClick = () => {
Removed console.log

2024-03-28 05:54 UTC, rajiravenantech commented on src/app/components/Sidebar/Sidebar.tsx
>                  Admina
Change the logo color and font size

2024-03-28 05:55 UTC, rajiravenantech commented on src/app/globals.css
> +  color: #fff;
Changed the active menu color

2024-03-28 12:01 UTC, esakkirajaravenantech approved these changes

2024-03-28 12:01 UTC, merged